name: 'Pull Request Linter'
description: 'Ensures your PR title matches a given regex'
author: 'Labelbox'
inputs:
  title-regex:
    description: 'Regex to ensure PR title matches. Allows anything by default.'
    required: true
    default: '.*'
  on-failed-regex-comment:
    description: 'Comment for the bot to post on PRs that fail the regex. Use %regex% to reference regex.'
    required: true
    default: 'PR title failed to match %regex%.'

runs:
  using: docker
  image: Dockerfile
