name: pr-lint
on: [pull_request]

jobs:
  pr-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: morrisoncole/pr-lint-action@v0.1.2-alpha
      with:
        title-regex: "#EX-[0-9]+"
        on-failed-regex-comment: "This is just an example. Failed regex: %regex%!"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
