name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Run local create-jira action"
        id: pr-lint
        uses: ./
        with:
          title-regex: '^\[[A-Z]+-\d*\](\ )'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
