name: PR Lint

on:
  - pull_request

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Run local create-jira action"
        id: pr-lint
        uses: ./
        with:
          title-regex: '\[[A-Z]+-\d*\]'
          on-failed-regex-comment: 'PR Title does not have a Jira issue (ex. [ENG-123]). Please add a Jira issue surrounded by [] anywhere in the title'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
